### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by amon28** [fengberd/MinecraftPEServer#32]
![screenshot_2016-10-15-14-46-58](https://cloud.githubusercontent.com/assets/22851168/19408047/435b14fa-92e6-11e6-9c06-34848a3075d9.png) i keep receiving the crashes whenever I press touch

**Comment by nnnlog** [comment]
This is Genisys' file Error
Plz upload and new issues on Genisys' issue

**Comment by Johnmacrocraft** [comment]
@ParkChanSol Nope, I'm not master at PHP but I think @amon28 installed PHP5 version of Slapper instead of PHP7. The error happened while loading Slapper with "Float", which happens when we load PHP5 plugin which contains class names like that. @amon28, could you upload crash dump for more information?
(아니요, PHP 방면에서 마스터는 아니지만 @amon28님이 PHP5 버전의 Slapper를 설치하신 것 같습니다. 오류가 Slapper를 로드하는 중 발생하였고, Float 클래스 오류 (치명적인 오류: pocketmine\nbt\tag\Float는 phar:///storage/emulated/0/PocketMine/plugins/plugin-1267.phar/src/slapper/main.php의 18번째 줄에서 특별한 클래스 이름이기에 Float으로 사용할 수 없습니다)

**Comment by nnnlog** [comment]
@Johnmacrocraft Oh, I see

**Comment by fengberd** [comment]
That might caused by your slapper plugin
