### ISSUE TITLE
Accepting the License

### ISSUE THREAD

**Issue by KevinLong021** [fengberd/MinecraftPEServer#99]
Maybe I am missing something obvious but I cannot figure out how to accept the GenysisPro license. I select the language in the console but then it says I must accept the license. How am I supposed to do this?

**Comment by fengberd** [comment]
Type y and click send for 2 times,make sure you didn't send/type anything
else,this works for me.


Best Regards,
FENGberd
------
This email together with its attachment(s) contain privileged or
confidential information.  If you are not the intended recipient or
unauthorized, please do not read, save, print, copy, retransmit, publish or
otherwise use the information of this email and the attachment(s).  Also,
please indicate to the sender that you have received this email in error,
and delete the copy you received.  We assume no liability for any loss,
damage, disruption, or delay incurred, or viruses effected whilst this
email is transmitted through internet, servers, systems, or otherwise not
in our control. We shall not be liable for the message if modified.
